name: Release Gitea runner
on: [push, workflow_dispatch, pull_request]

env:
  SLUG: ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USER }}/runner
  GITHUB_SERVER_URL: https://git.sogga.dev

jobs:
  build-oci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Authenticate with registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ secrets.REGISTRY_URL }}
      #     username: ${{ secrets.REGISTRY_USER }}
      #     password: ${{ secrets.REGISTRY_PASS }}

      - run: |
          docker login \
              -u ${{ secrets.REGISTRY_USER }} \
              -p ${{ secrets.REGISTRY_PASS }} \
              ${{ secrets.REGISTRY_URL }}

      - run: |
          case "${{ env.TAG }}" in
            latest)
              echo "VERSION=dev-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            ;;
            v*)
              echo "VERSION=v${{ env.TAG }}" >> $GITHUB_ENV
            ;;
            *)
              echo "VERSION=dev-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            ;;
          esac

      - run: |
          docker buildx bake \
            --push \
            .
