name: checks
on: 
  - push
  - pull_request

env:
  GOPROXY: https://goproxy.io,direct

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: actions/checkout@v3
      - name: vet checks
        run: make vet
      - name: build
        run: make build
      - name: test
        run: make test